### PR TITLE
Override settings for different languages

### PR DESCRIPTION
**Pull request by mseimys**
Allows to provide different settings for different languages.

Tried doing a `"scope": "resource"`, but got lost due to the fact that if you have separate folders, e.g.
```
python/
  .vscode/
    settings.json
  test_module.py
javascript
  .vscode/
    settings.json
  node_modules/
  module.spec.js
```
You would need to execute the commands in their own "workspace" folder, so all the commands should become something like `pushd ${folderName}; baseCommand + runOnCursorCommand; popd`. Anyway, here's [a good example](https://github.com/microsoft/vscode-extension-samples/tree/master/basic-multi-root-sample) on resource setting, if you are up for the challenge. Maybe I'm looking at it the wrong way :)

### CODE REVIEW

**Comment by gediminasz** [comment]
Thanks for the MR!

Regarding `"scope": "resource"`, you would have to create a new multi root workspace and add each folder individually to it, even if they're all part of the same monorepo. Then e.g. you could have two Python projects in the same workspace using different test frameworks (e.g. one uses pytest, the other one unittest from standard library).

I wonder if `"scope": "resource"` also allows the settings to be language overridable? That is, can we solve your problem and also have the possibility to set up multi root workspaces?

**Comment by mseimys** [comment]
Since I haven't worked with multi project workspaces, I don't even know how the structure should look ;) Here's a sample [project with settings.json](https://github.com/mseimys/test-workspace/blob/master/.vscode/settings.json) that I experimented on. I think justTesting would face problems with workspaces, because commands would need to be executed relative to file's "workspace folder". 

> I wonder if `"scope": "resource"` also allows the settings to be language overridable?

Yeah, they do work, but then settings themselves are underlined with squiggly line telling user that `This setting does not support per-language configuration.`

**Comment by gediminasz** [comment]
> Yeah, they do work, but then settings themselves are underlined with squiggly line telling user that This setting does not support per-language configuration.

I see. Looks like vscode won't let us have it both ways.

Regarding multi-root workspaces, you can use this menu item to add folders to a workspace:

image

What's nice is that each such folder can have its own `.vscode` configuration, but that requires [extra effort to implement on the extension side](https://github.com/microsoft/vscode/wiki/Adopting-Multi-Root-Workspace-APIs).

Screenshot 2020-04-12 at 12 39 03

See also https://code.visualstudio.com/docs/editor/multi-root-workspaces 

Anyway, language-overridable does the job so unless you want to change your habits and switch to multi-root workspaces, we can merge this and I'll make a new version release! 😄 Also you can update the changelog.md if you want, feel free to add a `0.7.0` section.

**Comment by mseimys** [comment]
Yeah, I played a bit with multi-root, but figured I don't like them that much. If a need arises, I just open multiple windows and Alt+Tab between them. Updated the changelog and readme, no clue how to release them :) comment if you want something more changed.

Closes #2

**Comment by gediminasz** [comment]
Looks good! 👌 Thanks again! I'll make the release.

**Pull request merged**
